clc;
clear;
close all;
tic;

%% import STL
[v, f, n, c, stltitle] = stlread('Exhaust_Mixer_Part.stl');          %STL import
close all;    %closing plots generated by function 
pts = unique(v,'rows');
pts_proj = [(pts(:,1)-pts(:,2))/2,(pts(:,2)-pts(:,1))/2,pts(:,3)];

%% specifying data for point grid
x_span = 100;
z_span = 100;
ptsgap= 2;
pts_proj = GridPoints(x_span,z_span,ptsgap);            %gives grid points along plane

%% projecting grid onto the STL surface
store_main = Grid_Pojection(v,f,pts_proj);

%% getting path from projected points
[storesort0x1,CELL] = Path_Direction(store_main);

%% plotting path over STL file
figure('Name','main_fig','units','normalized','outerposition',[0 0 1 1])       %new plot directly maximized window
col_matrix = [0.7, 0.7, 0.7];   %color for new plot
daspect([1,1,1])            %putting aspect ratio to be 1:1:1
patch('Faces',f,'Vertices',v,'FaceVertexCData',col_matrix,'FaceColor',col_matrix, 'EdgeAlpha', 0.5);
xlabel('X-Axis')
ylabel('Y-Axis')
zlabel('Z-Axis')
view(3)             %directly viewing plot in 3D
hold on;
for i = 1:size(CELL,1)
    mat = CELL{i,1};
    plot3(mat(:,1),mat(:,2),mat(:,3),'g','LineWidth',2);
    hold on;
    pause(0.1)
end

%% Writing data to different text files
Write_Data(CELL);

fprintf('--------------------------Done!-------------------------------\n')
toc;